### PR TITLE
Use getScheme() to compare against https.

### PR DESCRIPTION
**Pull request by spencergibb**
fixes gh-750

### CODE REVIEW

**Comment by tbak** [comment]
@spencergibb Thank you for the fix.

**Comment by spencergibb** [comment]
@tbak closed but not merged?

**Comment by spencergibb** [comment]
thanks!

**Comment by tbak** [comment]
Sorry, my mistake. It is merged now.

**Comment by spencergibb** [comment]
NP @tbak, we appreciate the work and super fast turn around!

**Pull request merged**
