### PR TITLE
refactor: JUnit Jupiter migration from JUnit 4.x

### PR DESCRIPTION
**Pull request by jkschneider**
👋 This PR will get you most of the way there to JUnit 5 from JUnit 4. We'd just need to migrate `DiscoveryClientResource` and `SimpleEurekaHttpServerResource` which don't have direct analogs in JUnit 5. Shouldn't be very difficult to complete from here, but hopefully this takes away most of the grueling work.

Co-authored-by: Moderne <team@moderne.io>

### CODE REVIEW

**Comment by troshko111** [comment]
This looks pretty harmless / low risk, but at the same time I wonder what the benefits are?

**Comment by jkschneider** [comment]
Hi @troshko111. Just trying to help so Eureka isn't built on a stale unsupported core testing framework? Feel free to close if you wish.

**Comment by troshko111** [comment]
I went over the PR and it looks good to me, I don't really see any issue with using `JUnit 4` regardless of its support status as it's not part of the running service, so there's no risk of CVEs and such, basically it does not matter how (un)supported it is, it works just fine. 

Given the number of new tests written, and potential benefit of using the new `JUnit` version there, such effort is unlikely to ever pay off, but it's already done so why not. Re-running and merging if all passes.

**Comment by troshko111** [comment]
Oh I see what you meant in the original PR message, this _does require changes before it can land_ (it does not compile as-is due to those two types not being migrated). In this case I can keep it open in case you / anyone else wants to drive it past the finish line, but I don't remember anyone expressing interest before, so if you won't be getting it into a mergeable state, I will probably close.

**Comment by jkschneider** [comment]
Feel free to close. It's a disappointing attitude toward the codebase, to be honest, and adds to the feeling that Eureka may be barely maintained. I thought having done most of the heavy lifting, it would be an easy win.

**Comment by troshko111** [comment]
It's unfortunate you feel this way, but in general we prefer _compiling PRs_ (all checks must pass), if this was a high value change I could see us taking it from here, but per my earlier response the value is debatable plus this does not compile, so closing. In the future, one easy way to avoid this situation is to open an issue first, have a discussion and alignment, and only then proceed with heavy lifting, once it's clear the change/scope is agreed upon.

**Pull request closed without merging**
