### PR TITLE
EUREKA-1087 Add one more check for "is this my url", so that even whe…

### PR DESCRIPTION
**Pull request by mgtriffid**
…n each node is behind ELB, heartbeats are not replicated to the node they originally were sent to

### CODE REVIEW

**Comment by qiangdavidliu** [comment]
@mgtriffid thanks for the PR. We will take a look at this.

**Comment by mattnelson** [comment]
Can the existing instance id be used for self identification? It is already a unique identifier.

Introducing a new endpoint complicates deployment considerations with rollout of this feature and adds more complexity. Additionally, eureka is already pretty chatty between the peers and with heartbeats. I would like to explore other options that don't add more requests.

**Comment by mgtriffid** [comment]
@mattnelson , probably, yes, existing instance id should work.
Speaking of not introducing new requests. When Eureka resolves addresses of peers through DNS, hosts in txt records are the only information it has. Sorry, I don't understand, how can Eureka find corresponding instance ids if not trying these hosts?
Maybe there already exists some request from which we could understand if caller == callee? If so, could you please suggest, where should I look?

Speaking of peers being chatty - please note that these requests are executed only for some short time after deployment, until Eureka finally calls itself and understands "yeah, this peer is actually me". After that, these requests don't happen.

Speaking of complicated deployment - yes, adding new resource to web server is required. But gradual rollout shouldn't be a problem: at some point Eureka will finally call itself (and if Eureka has this check - it means it has endpoint too), will figure out that called peer is actually the same node, and will stop doing these requests.

Overall, I certainly understand that this looks like a kludge, would be happy to find better solution.

**Comment by qiangdavidliu** [comment]
@mgtriffid I think @mattnelson raise some good points here about additional complexity that would be involved with this change. Does your deployment model support node specific configs? If so, the below strategy may be an easier way of achieving the same goal:
1. introduce a config variable that can be set to override the isThisMe url that is checked at https://github.com/Netflix/eureka/blob/master/eureka-core/src/main/java/com/netflix/eureka/cluster/PeerEurekaNodes.java#L246. Doing this eureka nodes can be configured to match on custom names that does not have to be the local hostname.
2. in your deployment, set this config to be the ELB hostname that correspond to each node.

**Comment by mgtriffid** [comment]
@qiangdavidliu , @mattnelson , thanks for ideas! Yes, this option with new configuration parameter is certainly much easier. Submitted new PR https://github.com/Netflix/eureka/pull/1107, declining this one.

**Pull request closed without merging**
