### PR TITLE
 remove  Response's Status magic var

### PR DESCRIPTION
**Pull request by Yangdaidai**
remove  Response's Status magic var

### CODE REVIEW

**Comment by Yangdaidai** [comment]
remove  Response's Status magic var

**Comment by Yangdaidai** [comment]
remove  Response's Status magic var

**Comment by Yangdaidai** [comment]
remove  Response's Status magic var

**Comment by troshko111** [comment]
Seems reasonable, but can you please split into 2 PRs? The changes seems unrelated right now.

**Pull request closed without merging**
