### PR TITLE
make constructor public so other DI systems can create instances

### PR DESCRIPTION
**Pull request by spencergibb**

### CODE REVIEW

**Comment by spencergibb** [comment]
Ping

**Comment by qiangdavidliu** [comment]
@spencergibb apologies for the lag, there's been a flurry of activity on eureka recently. We are a bit reluctant to make this constructor public available as that can lead to potential multiple instantiations. Which DI system in particular did you have in mind for this?

**Comment by spencergibb** [comment]
No problem! Spring.  Specifically Spring Cloud Netflix.  In [this PR](https://github.com/spring-cloud/spring-cloud-netflix/pull/356) we [do](https://github.com/spring-cloud/spring-cloud-netflix/blob/eureka-di/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClientConfiguration.java#L194-L198)

```
Constructor<ApplicationInfoManager> constructor = ApplicationInfoManager.class
				.getDeclaredConstructor(EurekaInstanceConfig.class, InstanceInfo.class);
ReflectionUtils.makeAccessible(constructor);
return constructor.newInstance(instanceConfig, instanceInfo);
```

**Comment by qiangdavidliu** [comment]
@spencergibb merged. Thanks. There a few other small things and we should make a patch release soonish.

**Comment by spencergibb** [comment]
Thanks @qiangdavidliu!

**Pull request merged**
