### PR TITLE
Add the ability to use additional Jersey ClientFilters in the DiscoveryClient

### PR DESCRIPTION
**Pull request by willtran-**
So we can do things like add Authorization headers and authenticate those on the Eureka Server

### CODE REVIEW

**Comment by qiangdavidliu** [comment]
Hi @willtran- can you please do a rebase? Thanks.

**Comment by willtran-** [comment]
done

**Comment by willtran-** [comment]
Hey @qiangdavidliu what do you think of this PR?

**Comment by qiangdavidliu** [comment]
@willtran- looks good, thanks for the contribution.

**Pull request merged**
