### PR TITLE
async anonymous class change to implements Runnable interface class.

### PR DESCRIPTION
**Pull request by qq1036916439**
better read

### CODE REVIEW

**Comment by troshko111** [comment]
This looks like a readability and API regression to me:

- Introduces a public type which is not a contract for no apparent reason
- Requires to jump to a different file to read the logic

**Comment by qq1036916439** [comment]
Can I use lambda or private inner classes?

**Comment by troshko111** [comment]
Yes, don't see why not, it's a negligible change though, but legit.

**Comment by qq1036916439** [comment]
I think that inner class should not call outer class in this way.
    `InstanceInfoReplicator.this.run(); `
 I have never seen such a way before.
I am looking at the code of Eureka and hope to provide some help for Eureka. Although only trivial.

**Pull request closed without merging**
