### PR TITLE
Fix issue #756 (restore HTTP authentication support)

### PR DESCRIPTION
**Pull request by tbak**

### CODE REVIEW

**Comment by tbak** [comment]
@kennedyoliveira Here is the fix restoring basic authentication. Most of the code there is the test code, to make sure we do not miss this feature in the future. We do not use HTTP basic authentication as it is inherently insecure.

**Comment by spencergibb** [comment]
Thanks @tbak, we have folks that use it in conjunction with SSL.  Looks good!

**Comment by kennedyoliveira** [comment]
@tbak, thank you very much! I know it's not safe, but i was planing to use with SSL as @spencergibb, there is any alternative to this method for eureka?

**Comment by spencergibb** [comment]
There's some SSL certificate security, but other than that...

**Comment by tbak** [comment]
@kennedyoliveira We are using client side certificates, to authenticate both sides of the connection.

**Comment by qiangdavidliu** [comment]
:+1:

**Comment by kennedyoliveira** [comment]
@tbak, sounds interesting, how is that?

**Comment by tbak** [comment]
@kennedyoliveira Sorry, I have to take it back about the client side certificate validation. There are however some ways to do that (via SSL system properties or creating custom EurekaJerseyClient).

**Comment by kennedyoliveira** [comment]
@tbak, hmm i will search about that, i don't know much about SSL, just the basic, anyway, thank you for fixing it! If you have any source of documentation/books/ anything about this case and could tell me, i appreciate :D

**Pull request merged**
