### PR TITLE
Upgrade nebula.netflixoss to replace bintray publication and update TravisCI Secrets

### PR DESCRIPTION
**Pull request by rpalcolea**
Hi folks,

As you might be aware, JFrog is sunsetting Bintray and JCenter: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

This upgrades to Nebula NetflixOSS which will publish to Nebula's OSS repos and Maven Central.

Repositories based on status:

* https://netflixoss.jfrog.io/artifactory/maven-oss-snapshots
* https://netflixoss.jfrog.io/artifactory/maven-oss-candidates
* https://netflixoss.jfrog.io/artifactory/maven-oss-releases

### CODE REVIEW

**Review by troshko111 — APPROVED** [review]

**Comment by troshko111** [comment]
I can do a release (there are unreleased changes) to try this out, would appreciate if you could help verify.

**Comment by rpalcolea** [comment]
yeah that makes sense, I can verify that everything goes as expected

**Comment by troshko111** [comment]
@rpalcolea kicked off https://github.com/Netflix/eureka/releases/tag/v1.10.13

**Comment by rpalcolea** [comment]
Alright I see https://repo1.maven.org/maven2/com/netflix/eureka/eureka-core/1.10.13/  in maven central

and also in our repo: https://repo1.maven.org/maven2/com/netflix/eureka/eureka-core/1.10.13/ 

Same for other modules such as:

https://repo1.maven.org/maven2/com/netflix/eureka/eureka-server/1.10.13/
https://repo1.maven.org/maven2/com/netflix/eureka/eureka-client/1.10.13/

**Pull request merged**
