### PR TITLE
Log a version warning if not being run under Java 1.8

### PR DESCRIPTION
**Pull request by jamesmulcahy**

### CODE REVIEW

**Comment by spencergibb** [comment]
Shouldn't it be at **least** Java 8?

**Comment by jamesmulcahy** [comment]
Is anyone running with Java > 8 today? All the docs mention 1.8, which is why I chose to be specific about 1.8 here.

I wasted a bunch of time in the last couple of days tracking down what turned out to be an issue running Java >= 11, so I know that doesn't work.

**Comment by spencergibb** [comment]
Spring Cloud supports Java 8+ with integration tests for 11 and 14. We have users running on 11+. What was the specific issue?

**Comment by jamesmulcahy** [comment]
Interesting context, thanks @spencergibb.  Does Spring Cloud run the eureka-server under 11+14, or just the client?

The error Tomcat throws is:

```
21-Sep-2020 12:35:12.654 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [jersey]
	java.lang.TypeNotPresentException: Type javax.xml.bind.JAXBContext not present
		at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
		at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
		at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
		at java.base/sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
		at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
		at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
		at java.base/sun.reflect.generics.repository.ClassRepository.computeSuperInterfaces(ClassRepository.java:117)
		at java.base/sun.reflect.generics.repository.ClassRepository.getSuperInterfaces(ClassRepository.java:95)
		at java.base/java.lang.Class.getGenericInterfaces(Class.java:1156)
		at com.sun.jersey.core.reflection.ReflectionHelper.getClass(ReflectionHelper.java:629)
		at com.sun.jersey.core.reflection.ReflectionHelper.getClass(ReflectionHelper.java:625)
		at com.sun.jersey.core.spi.factory.ContextResolverFactory.getParameterizedType(ContextResolverFactory.java:202)
		at com.sun.jersey.core.spi.factory.ContextResolverFactory.init(ContextResolverFactory.java:89)
		at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1332)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180)
		at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799)
		at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795)
		at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
		at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790)
		at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:509)
		at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:339)
		at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
		at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
		at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:394)
		at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:744)
		at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
		at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
		at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:106)
		at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4538)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1840)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at java.base/java.lang.Thread.run(Thread.java:832)
	Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1358)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:427)
		at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
		... 41 more
21-Sep-2020 12:35:12.910 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
21-Sep-2020 12:35:12.910 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
21-Sep-2020 12:35:12.911 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@7d23879e')
21-Sep-2020 12:35:16.989 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log SessionListener: contextDestroyed()
21-Sep-2020 12:35:16.989 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextDestroyed()

```

This works fine without the eureka-server loaded; so while the stack trace doesn't mention eureka, it certainly triggers the issue.

**Comment by spencergibb** [comment]
We run the server. See https://github.com/spring-cloud/spring-cloud-netflix/blob/0665640c9787a42a32624245bb0f2e23b411f358/spring-cloud-starter-netflix-eureka-server/pom.xml#L29-L33

We add the appropriate dependency that doesn't hurt in java 8

**Comment by jamesmulcahy** [comment]
I've replicated that in the build.gradle within eureka-server, in #1342, closing this in preference to that.  Doesn't seem like any other changes are required (and I'd previously been weary of going down this path for fear of finding a big list of issues).  Thanks for the input @spencergibb

**Pull request closed without merging**
