### PR TITLE
Bump default connection idle timeout

### PR DESCRIPTION
**Pull request by fiibbb**
Bump default connection idle timeout to 45 seconds.

### CODE REVIEW

**Comment by spencergibb** [comment]
Again, why change the default when you can change it via configuration?

**Comment by troshko111** [comment]
@spencergibb 
> Again, why change the default when you can change it via configuration?
I think it makes sense to change the default in this particular case as the default was improperly chosen. The default polling interval is `30s` and the client configures to close its socket on `30s` of inactivity which basically creates a race and may cause it unnecessary bounce among Eureka servers making keep alive useless. WDYT?

**Comment by spencergibb** [comment]
Sounds good

**Review by troshko111 — APPROVED** [review]

**Comment by mattnelson** [comment]
> The default polling interval is `30s` and the client configures to close its socket on `30s` of inactivity which basically creates a race and may cause it unnecessary bounce among Eureka servers making keep alive useless. WDYT?

Should eureka log a message if this configuration is detected?

**Pull request merged**
