### PR TITLE
Upgrade Jackson to the next open branch 2.10

### PR DESCRIPTION
**Pull request by AmitAmar**

### CODE REVIEW

**Comment by troshko111** [comment]
That's 3 branches up, which includes quite a few changes, it'd need to have some wider validation. Is staying on `2.9.x` viable for you?

**Comment by AmitAmar** [comment]
Hi,

Thanks for your reply.

Unfortunately,  I didn't understand your question.

I had upgrade the jackson version from: 2.9.10 --> 2.12.3 because some
vulnerability (according to WhiteSource)

[image: image.png]

Can you please explain yourself?

Thanks and have a nice day,

Amit.

‫בתאריך יום ב׳, 17 במאי 2021 ב-19:59 מאת ‪troshko111‬‏ <‪
***@***.***‬‏>:‬

**Comment by troshko111** [comment]
Sure, so Jackson has a number of "branches" in development, which differ in behavior (mostly minor but noticeable), see https://github.com/FasterXML/jackson/wiki/Jackson-Releases

We're on `2.9` branch which is closed so won't get new vulnerability patches, meaning we need to move on, agreed. But in your PR you're skipping through https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.10#changes-compatibility and https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.11 completely - note the list of changes and incompatibilities.

What I'm saying, the users or even Eureka may not work as expected and we need to double check those changes / compatibilities don't break anything.

It may be easier to do one step at a time, and move to `2.10` branch instead (it should have the patches for the current CVEs), and only verify that branch changes don't break anything, then in the future we can move to `2.11` and so on (until we're current).

Does it make sense?

**Comment by AmitAmar** [comment]
Hi there,

Thank you for your explanation. Yes it makes sense to upgrade to 2.10
instead of 2.13. you're right.

Can you please change it or I'll send a new PR?

Thank you and have a nice day,

Amit.

‫בתאריך יום ג׳, 18 במאי 2021 ב-0:45 מאת ‪troshko111‬‏ <‪
***@***.***‬‏>:‬

**Comment by troshko111** [comment]
Keep the PR, feel free to push a new commit.

**Comment by troshko111** [comment]
Superseded by #1393.

**Comment by AmitAmar** [comment]
Done :)

https://github.com/Netflix/eureka/pull/1395

BR,

Amit.

‫בתאריך יום ג׳, 18 במאי 2021 ב-22:06 מאת ‪troshko111‬‏ <‪
***@***.***‬‏>:‬

**Pull request closed without merging**
