### PR TITLE
Capture "CacheRefreshed" event

### PR DESCRIPTION
**Pull request by brenuart**
The objective is to capture "cache refreshed" events. A few comments (following discussion in https://github.com/Netflix/eureka/issues/545):

1/ Added protected methods invoked when remote status is changed and cache is refreshed. They  are currently responsible to fire the appropriate event to the EventBus if one is available.
They are intentionally made protected so subclasses of the `DiscoveryClient` can override them if they need more advanced behaviour like:
- implement the Observer pattern and invoke registered listeners/observers
- compute actual changes when cache is refreshed
- etc

2/ I could create a `CacheRefreshedEvent` similar to the existing `StatusChangedEvent` and fire it every time the cache is refreshed. However, I'm not sure about the implications this additional event may have on components currently listening to the only StatusChangedEvent... What is your opinion?

3/ The `FETCH_REGISTRY_TIMER` includes the time taken by the following bloc of code:

     private boolean fetchRegistry(boolean forceFullRegistryFetch) {
         try {
            ....
            // Notify about cache refreshed before updating the instance remote status
            onCacheRefreshed();
            
            // Update remote status based on refreshed data held in the cache
            updateInstanceRemoteStatus();
       } catch(Throwable t) {
       ....
       } finally {
           tracer.stop();

The tracer includes the time it takes to notify listening parties. Should't we stop the timer before?

4/ I could have introduced the `Observer` pattern directly. But then I think it should have been done for both the `StatusChangedEvent` AND the newly introduced `CacheRefreshedEvent`...
They new protected methods are good starting point to build the Observer pattern if needed.

### CODE REVIEW

**Comment by brenuart** [comment]
Don't see why the test failed - cannot reproduce the failure locally.
Just wondering if it is not a timing issue?

**Comment by qiangdavidliu** [comment]
Thanks @brenuart . I restarted the test and it looks like it was a transient failure.

On your comments:

1/ Agree.

2/ Messages published on the event bus can be consumed with the following recipe:
```java
// Here I am using an anonymous inner class to reduce verbosity of the example, in reality, although this works, you may want to have a named class.
eventBus.registerSubscriber(new Object() {
    // Any method annotated with @Subscribe will be a consumer of the event class (or any subclass thereof), which is the first (and only) argument in the method.
    @Subscribe
    /* Any access modifier & any method name works. You do not have to implement any interface */
    public void consume(MyEvent event) {
        // Consumption of the event code.
    }
});
``` 
So the consumers can listen for specific event types without interfering with the consumers of different event types.

Another example to look at for event bus consumption is [EurekaUpStatusResolver](https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/EurekaUpStatusResolver.java)

3/ You are correct on this. I guess right now since EventBus publish and consumption is async it doesn't make a big difference.

4/ Agree.

**Comment by brenuart** [comment]
Additional modifications after your comments:

(point 2) 
A new `CacheRefreshedEvent` has been created and is automatically published by the `DiscoveryClient` if an `EventBus` is provided.
I also made the `StatusChangeEvent` and `CacheRefreshEvent` inherit from the same parent `DiscoveryEvent`. Having a common parent for all events sent by the same source is quite convenient.

(point 3)
I moved the code not directly related to the refresh of the local cache outside of the scope of the timer.

**Comment by qiangdavidliu** [comment]
Thanks @brenuart

**Pull request merged**
