### PR TITLE
Fix null pointer exception(#1427)

### PR DESCRIPTION
**Pull request by wcnnkh**

### CODE REVIEW

**Review by troshko111 — APPROVED** [review]

**Comment by troshko111** [comment]
Test failing, does it pass for you locally?

**Comment by wcnnkh** [comment]
> Test failing, does it pass for you locally?

Not tested locally because I don't have a gradle environment. But why is such a simple modification wrong? I haven't seen that the error is related to my modification. I'll test it after I install the environment.

**Comment by spencergibb** [comment]
No need to install Gradle, just run the wrapper at the root of the project

**Comment by troshko111** [comment]
> Not tested locally because I don't have a gradle environment. But why is such a simple modification wrong? I haven't seen that the error is related to my modification. I'll test it after I install the environment.

Well good question, I admit that Gradle does an amazing job burying any useful information in the sea of output it produces, but after wasting some good 5m I managed to locate the failure:

```
com.netflix.eureka.util.StatusUtilTest > testGetStatusInfoUnsetHealth FAILED
    java.lang.AssertionError: Excpected NPE to be thrown when healthy threshold is not set
        at org.junit.Assert.fail(Assert.java:88)
        at com.netflix.eureka.util.StatusUtilTest.testGetStatusInfoUnsetHealth(StatusUtilTest.java:52)
```

Looks like there's a test asserting the existing behavior in `eureka-core/src/test/java/com/netflix/eureka/util/StatusUtilTest.java` method `testGetStatusInfoUnsetHealth`.

And apparently
`eureka-core/src/main/java/com/netflix/eureka/util/StatusUtil.java` does:

```
        // Only set the healthy flag if a threshold has been configured.
        if (peerEurekaNodes.getMinNumberOfAvailablePeers() > -1) {
            builder.isHealthy(upReplicasCount >= peerEurekaNodes.getMinNumberOfAvailablePeers());
        }
```

So there's a dependency on the existing behavior.

I'm inclined to decline the change based on this, unless you provide more information on how this affects any real use case / how to trigger this NPE.

**Pull request closed without merging**
