### PR TITLE
use shutdownNow() instead of shutdown()

### PR DESCRIPTION
**Pull request by klues**
shutdown() does not prevent execution of previously submitted tasks, which can cause that AsyncResolver.shutdown() does not really shutdown all tasks -> memory leak

### CODE REVIEW

**Comment by klues** [comment]
see https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html#shutdown() for effects of shutdown() and shutdownNow()

**Comment by pauldburton** [comment]
This solved the same issue in our shared tomcat environment is there any chance of it being merged?

**Comment by klues** [comment]
I built my own release containing this fix and we are using it in our project. I don't know why it is not being merged. If you need the release containing the fix and you don't want to build it on your own just contact me.

**Comment by TatsianaKTV** [comment]
Hi @klues . If it possible give me please credentials for your eureka realise fix. Thanks.

**Comment by klues** [comment]
see https://github.com/klues/eureka/tree/jar-containing-memory-leak-fix/bin for my built release containing this fix

**Comment by TatsianaKTV** [comment]
@klues thanks.

**Comment by qiangdavidliu** [comment]
@klues thanks for the contrib.

**Pull request merged**
