### PR TITLE
Added ENI aws binder

### PR DESCRIPTION
**Pull request by jc89**
Added binder for aws elastic network interfaces.
This is done creating an AWSBinder and modifying the delegate to properly choose using the new binder strategy

### CODE REVIEW

**Comment by qiangdavidliu** [comment]
@jc89 thanks for the PR. Could you please also add some comments to specify what the expected DNS records would look like, and what tags the ENIs will need to be tagged with? Thanks.

**Comment by jc89** [comment]
@qiangdavidliu a few dns record examples:

txt.us-east-1.eureka="us-east-1a.eureka" "us-east-1b.eureka"
txt.us-east-1a.eureka="ip-172-31-y-y.ec2.internal"
txt.us-east-1b.eureka="ip-172-31-x-x.ec2.internal"

where "ip-172-31-x-x.ec2.internal" is the ENI private dns

No tags are requiered for the enis, just like with elastic ips, are deduced from service urls or dns records.

I will add more later

**Comment by jc89** [comment]
If you'd like t configure it via service urls, the service urls should look like this

```
eureka.awsBindingStrategy=ENI
eureka.serviceUrl.us-east-1a=http://ip-172-31-35-108.ec2.internal:7001/eureka/v2/
```

**Comment by qiangdavidliu** [comment]
Thanks again @jc89. Would you mind adding what you just described as javadoc comments to the Top of the ENIBinder class? That way the documentation will live with the code.

Otherwise everything looks fine, and I'll merge this in as soon as you add the documentation.

**Comment by jc89** [comment]
@qiangdavidliu Done

**Comment by qiangdavidliu** [comment]
@jc89 thanks for the contrib.

**Pull request merged**
