### PR TITLE
change overriddenstatus field name in pojo to allow for better serialization compatibility

### PR DESCRIPTION
**Pull request by qiangdavidliu**
further relax deser behaviour on overriddenstatus field to allow for both lower and camel case

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
@spencergibb I think this will fix https://github.com/spring-cloud/spring-cloud-netflix/issues/2941, do you agree?

**Comment by spencergibb** [comment]
Yup

**Comment by spencergibb** [comment]
This didn't fix things for us, since ` @JsonProperty("overriddenstatus")` is still the lowercase version :-(

**Comment by qiangdavidliu** [comment]
I was wondering about that :(. Let me give it one last shot.

**Comment by spencergibb** [comment]
Changing that to camel case breaks tests in `EurekaCodecCompatibilityTest`

**Comment by spencergibb** [comment]
`Unrecognized field "overriddenstatus"`. The opposite of what we have. When you have something in a branch/fork somewhere, let me know, I'll build and try so we don't end up releasing it broken again.

**Pull request merged**
