### PR TITLE
Add the InstanceInfo to the response in case of 409 status code

### LINKED ISSUE #933: 409 Conflict Response does not send the InstanceInfo back to the client
In `InstanceResource`, when renewing a lease and `lastDirtyTimestamp` is not null, the code will return a 409 Conflict to the client in a certain situation. However, `PeerReplicationResource` will not return the `InstanceInfo` in the body of the response unless the status code is 200.

On the client side of things, `PeerEurekaNode` needs this `InstanceInfo` to execute the method `syncInstancesIfTimestampDiffers`. Since it's never sent back from the server, this code never gets executed and you get `The replication of task XXX/i-XXX@XXX failed with response code 409` logs until you fix it manually.

PR submitted.

### PR DESCRIPTION
**Pull request by jebeaudet**
Fixes #933.

Thanks!

### CODE REVIEW

**Comment by qiangdavidliu** [comment]
Thanks @jebeaudet, taking a look ...

**Comment by jebeaudet** [comment]
@qiangdavidliu Have you had the chance to give it a look? We're releasing this patch in our production environment soon and I'd sleep better if I had your green thumbs on it :wink:

**Comment by qiangdavidliu** [comment]
Hi @jebeaudet apologies for the delayed response. This PR looks sound and makes logical sense, but I want to set up a quick test in our test env to test this out just to verify any potential unintended side effects. I'll let you know soon.

**Comment by qiangdavidliu** [comment]
@jebeaudet prelim trial seems ok, though there were some weirdness. Will merge this. Thanks for the contrib!

**Comment by jebeaudet** [comment]
@qiangdavidliu Did you get a chance to test it enough to remove the failguard of https://github.com/Netflix/eureka/commit/6f3f997d640c32b2d391f6555a5cdaa7cd66e7c0?

**Comment by jebeaudet** [comment]
@qiangdavidliu Any info about that safeguard? Thanks!

**Pull request merged**
